// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbubPuqroZicQzAv5dXj5wxTIlUPy5gLI',
    appId: '1:679774883195:web:7e2927c7d5773d73a081de',
    messagingSenderId: '679774883195',
    projectId: 'flutter-albums',
    authDomain: 'flutter-albums.firebaseapp.com',
    storageBucket: 'flutter-albums.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPhHvW9dX0eQMxQe9WvE7uD88emhiz4Q',
    appId: '1:679774883195:android:6ee50eea3fa7db3ea081de',
    messagingSenderId: '679774883195',
    projectId: 'flutter-albums',
    storageBucket: 'flutter-albums.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAorUHaRYbRscv-YFZFYkP6fOyiiSawU',
    appId: '1:679774883195:ios:b8eb6d55a3df571fa081de',
    messagingSenderId: '679774883195',
    projectId: 'flutter-albums',
    storageBucket: 'flutter-albums.appspot.com',
    iosClientId: '679774883195-il4c9lgt0qcdvfe42q6ejq6snrrok0i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAorUHaRYbRscv-YFZFYkP6fOyiiSawU',
    appId: '1:679774883195:ios:b8eb6d55a3df571fa081de',
    messagingSenderId: '679774883195',
    projectId: 'flutter-albums',
    storageBucket: 'flutter-albums.appspot.com',
    iosClientId: '679774883195-il4c9lgt0qcdvfe42q6ejq6snrrok0i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
